#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May  1 09:59:51 2020

@author: katewujciak
"""

import FP time as time
import FP currency as cur
import Attractions as at
import Flight Time as ft